requests/httpbin

httpbin/helpers.py

There's no standard for the headers added by a reverse proxy when it handles
an https incoming request. Some proxies add `X-Forwarded-Proto` but others add
`X-Forwarded-Protocol` or `X-Forwarded-Ssl`. This change lets httpbin work with
reverse proxies use any of these headers. It also instructs httpbin to ignore
those headers because they're added by a proxy.
Fixes #207. @sigmavirus24 was correct, Heroku uses `X-Forwarded-Proto` but the
Runscope hosting platform uses `X-Forwarded-Protocol`.

Allow httpbin to recognize SSL connections from more reverse proxy headers

---

requirements.txt

`gunicorn==18.0` had previously been listed in requirements.txt, but I
removed it in commit d851a7e2a1a3239dd853ff88f918e1c52cf4b8f4 for
compatibility with the new httpbin.org hosting platform.
gunicorn 19.2 has (finally) been released, and this version will work
correctly for httpbin.org. This change adds `gunicorn==19.2` back to
requirements.txt.
This may also fix problems deploying to Heroku reported by @sigmavirus24,
which may have been caused by the requirement change in
d851a7e2a1a3239dd853ff88f918e1c52cf4b8f4.

Restore gunicorn in the list of third-party requirements

---

README.rst
httpbin/core.py
httpbin/helpers.py
httpbin/templates/httpbin.1.html
test_httpbin.py

A basic implementation of range requests:
http://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7233.html
Allows querying http://httpbin.org/range-request/1024?duration=s&chunk_size=code, specifying Range headers that allow selecting specific portions of the resource to GET.

Add range request functionality

---

README.rst
httpbin/templates/httpbin.1.html

This needs to be `https://www.hurl.it`:
❯ curl -IL https://hurl.it/
curl: (7) Failed to connect to hurl.it port 443: Connection refused
---
❯ curl -IL https://www.hurl.it/
HTTP/1.1 200 OK

Fix hurl.it links

---

httpbin/core.py
httpbin/helpers.py
httpbin/templates/forms-post.html
httpbin/templates/httpbin.1.html

Using url_for is useful if httpbin is served under a prefix path.  For
example, we can serve httpbin under http://example.org/httpbin.
Previously, we have to replace all hard coded paths, which produces
many diffs, and it makes hard to upgrade httpbin from source.  This
commit uses url_for to resolve correct path even if prefix path is
used.  For digest auth, we have to prepend request.script_root to
request.path to pass authentication.

Use url_for to resolve path instead of hard coding it

---

httpbin/core.py

Discovered when attempting to use pytest-httpbin with requests (see kennethreitz/requests#2184 and kevin1024/pytest-httpbin#27).
It turns out that the WSGI specification *specifically forbids* implementations from emitting the `Transfer-Encoding` header, as noted in [this part of PEP 333](https://www.python.org/dev/peps/pep-0333/#other-http-features) (emphasis in the original):
> WSGI applications **must not** generate any "hop-by-hop" headers, attempt to use HTTP features that would require them to generate such headers, or rely on the content of any incoming "hop-by-hop" headers in the `environ` dictionary.
Now, it's extremely clear that certain WSGI servers allow the use of generators to generate chunked transfer encoding, and gunicorn is one of them. More importantly, they do this …

Do not forcefully emit Transfer-Encoding header

---

httpbin/core.py

Apologies, but my last pull request, which was merged in https://github.com/Runscope/httpbin/commit/4763d4761407dce3a99be3c6640c14dcd4be30fe, was merged with a bug.
Since the int constraint is removed to allow for floats, the delay parameter comes in as unicode. 
I'm not exactly sure how the unicode is compared with the integer 10, but this obviously creates undesirable delays -- 10 ends up being smaller than whatever number the min function interprets the unicode as.
I've run this with delay between 1 - 10 and 0 - 1 and they all return 10.
Sorry again for the trouble. Hopefully there won't be any more.

Floating point type conversion

---

README.rst
setup.py

This is the separate PR for updating the changelog and setup.py file, as requested here: https://github.com/Runscope/httpbin/pull/266

Changelog and setup updated for floating point support 

---

requirements.txt

We recently updated the version of python we use internally to run httpbin and have upgraded gevent for this bug fix:
https://github.com/gevent/gevent/issues/477

Upgrade gevent to 1.0.2

---

tox.ini

This uses twine to upload wheels and source distributions that we create
for httpbin.

Add machinery to create/upload releases

---

httpbin/core.py

Because it is not present in Flask 0.11. We keep merging the headers from the `headers` variable with the headers from the `response.headers`, because changing the response may change the headers, especially the `Content-Length` header. In Flask 0.11 this `Content-Length` header is no longer present in the `response.headers`, so we check whether the `response.data` has changed.
Fixes #290

Don't check Content-Length header anymore

---

httpbin/core.py
test_httpbin.py

This is an idea for PR https://github.com/Runscope/httpbin/issues/283 it is sufficient for debugging the bug in https://github.com/kennethreitz/requests/issues/3079

Added supports for non-get redirect-to with other status_code

---

httpbin/core.py
httpbin/helpers.py
httpbin/templates/httpbin.1.html
test_httpbin.py

RFC 7616 specifies other algorithms for Http Digest:
http://tools.ietf.org/html/rfc7616
I've added support for multiple algorithms in the URLs:
Old:
https://httpbin.org/digest-auth/auth/user/passwd
New:
https://httpbin.org/digest-auth/MD5/auth/user/passwd
https://httpbin.org/digest-auth/SHA-256/auth/user/passwd

Added support for another Digest algorithm, SHA256.

---

setup.py

Fix for _UnicodeDecodeError_ of Python 3 when _setup.py_ is exectuted in non-UTF-8 environments with Python 2 backward compability.

use io.open() for long_description from file

---

httpbin/helpers.py

remove unused variable `form` from `helpers.get_dict`

remove unused variable `form` from `helpers.get_dict`

---

httpbin/helpers.py
test_httpbin.py

Fix typo in HA2() function, which caused Digest auth test to fail, when 'qop' parameter is set to 'auth-int'.

GH-307 Fix error 500 on digest auth with qop='auth-int'

---

test_httpbin.py

Response.get_data did not exist in older versions of Flask/Werkzeug,
and is even now not documented at the Flask level.
This will make httpbin work with either the new version where it does
exist, and the older versions where it doesn't.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

Use Response.data with older Werkzeug versions

---

httpbin/core.py

For 'range' requests, knowing the original content-length is important for some tests I'm running.  So I've added content-length to the returned headers, where that length is set to the value requested in the URL.

Return content-length in 'range' requests

---

httpbin/core.py
test_httpbin.py

Return HTTP 400 if drip parameter 'numbytes' is less or equal to zero, thus avoiding divide by zero error.

Fix error 500 on drip due to division by zero (issue #296)

---

httpbin/core.py
httpbin/filters.py
setup.py
test_httpbin.py

This pull request adds an endpoint that supports the [Brotli](http://google-opensource.blogspot.co.uk/2015/09/introducing-brotli-new-compression.html) compression algorithm used as a content-encoding, alongside the current support for gzip and deflate. Chromium have announced their [intention to implement](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/xdVm8c2GOMQ) Brotli, and Firefox 44 included [their support for Brotli](https://bugzilla.mozilla.org/show_bug.cgi?id=366559). Curl also [intend to implement Brotli](http://curl.haxx.se/docs/todo.html#More_compressions). I have opened this pull request myself because the urllib3 project intends to support Brotli as well (see shazow/urllib3#713), and we needed an endpoint to test against: httpbin seemed like a good choice. …

Add a Brotli endpoint.

---

Dockerfile

For ease of deployment it might be helpful to have a Docker container that runs httpbin. This is a simple first step down that road.
Before merging, it might be worth trying to optimise this image somewhat. For example, it might be better to use Debian as the base rather than Ubuntu. It might also be worth trying to remove the artifacts of the build step, make the number of gunicorn workers parameterizable, or something else interesting. I'm happy to make those changes and test them.

[RFC] Dockerize

---

httpbin/core.py
test_httpbin.py

This supersedes #345 by fixing the value for the Content-Length for the `/range` endpoint.

fix Content-Length header values for /range endpoint

---

httpbin/core.py
httpbin/helpers.py
httpbin/templates/httpbin.1.html
test_httpbin.py

I thought it would be interesting if a client could supply an entity tag in the URL and then httpbin would execute the appropriate conditional logic based on the request's `If-Match` and `If-None-Match` headers. 
Some examples in action: 
```
$ curl -I -H 'If-None-Match: "abc"' 'http://localhost:8080/etag/abc'
HTTP/1.1 304 NOT MODIFIED
$ curl -I -H 'If-None-Match: "abcd"' 'http://localhost:8080/etag/abc'
HTTP/1.1 200 OK
$ curl -I -H 'If-Match: *' 'http://localhost:8080/etag/abc'
HTTP/1.1 200 OK
$ curl -I -H 'If-Match: "abc"' 'http://localhost:8080/etag/abc'
HTTP/1.1 200 OK
$ curl -I -H 'If-Match: "efg"' 'http://localhost:8080/etag/abc'
HTTP/1.1 412 PRECONDITION FAILED
$ curl -I -H 'If-None-Match: "abc", "d", "efg"' 'http://localhost:8080/etag/efg'
HTTP/1.1 304 NOT MODIFIED
```
Since usage …

Adding a /etag URL for testing If-Match and If-None-Match conditional logic

---

httpbin/templates/httpbin.1.html

I needed an endpoint which returns content in chunked encoding (`Transfer-Encoding: chunked`), and through `curl`-ing around I found out that `stream-bytes` does that, so I thought it would be useful to document it.

Mention that "stream-bytes" uses chunked encoding

---

httpbin/core.py
httpbin/helpers.py
httpbin/templates/httpbin.1.html
test_httpbin.py

This makes it easier to test which HTTP method is being used, and also to test custom URLs.
Unfortunately, it isn't good for testing URLs with special Unicode characters in them, because Flask seems to automatically decode and unescape the URLs.

Add /anything route

---

httpbin/core.py

`/anything` already returns the used method, but only allows for `GET` requests.
With this extension `/anything` acts as an "echoserver" and additionally returns any sent data.

Allow all methods on /anything

---

httpbin/core.py
httpbin/helpers.py
httpbin/templates/httpbin.1.html
test_httpbin.py

Hi,
In this change digest authentication path is expanded by extra value `stale_after`.
This integer value will cause that after `stale_after` successful responses next response will report `401` with flag `stale=true` indicating that nonce value is no longer valid.
Also each `401` response stores last used `nonce` value in cookie, so if another request is received with same nonce value response with status code `401` and with flag `stale=true` is send back even if password is correct (nonce is considered as expired).
I've also refactor test a bit and added a new test to cover new functionality and added extra one for invalid credentials.
Hope you will consider this as useful change.
BR,
Marek

Digest authentication and expiried nonce - stale=true scenerio

---

Dockerfile

As @kennethreitz likes to say:
> The use of Python 3 is highly preferred over Python 2. Consider upgrading
> your applications and infrastructure if you find yourself still using Python
> 2 in production today. If you are using Python 3, congratulations — you are
> indeed a person of excellent taste.

Change base Dockerfile from Python 2 to Python 3

---

httpbin/core.py
httpbin/helpers.py

Our digest auth endpoint will once again return a fake cookie but will
only require it if the query-string parameter `require-cookie` is
present.
Further, this fixes a bug in the digest auth implementation in httpbin
where we were only considering the path portions of the request-uri in
the specification. RFC 7230 is very clear that the request-uri includes
the query-string if it is present which means it is necessary in our
digest auth handling.
Closes #380

Add back fake cookie and make requiring it conditional

---

setup.py

The rate limiting code has been ping ponged several times, but
currently it's not there, so there is no reason to require
flask-limiter.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Don't require flask-limiter

---

.travis.yml
tox.ini

Update Python interpreter used in Tox tests from py34 to py36.  3.6 seems to be what is used in the current Docker container.  Not sure what is deployed to sites.
Made equivalent changes to Travis config.  FWIW also locked dist to trusty, and added a matrix to split the 2.7 and 3.6 builds to use exactly those runtimes (possible the tox env was achieving this anyway).

Updated tox and Travis to use py36.

---

MANIFEST.in
setup.py

Tell unittest.discover specifically what to look for instead of letting
them scan the entirety of our directory (which could have other
dependencies downloaded with their tests that will fail).
Closes #403 
cc @0-wiz-0 if you can test my suggestion in #403 and verify that works, this is the equivalent and we can merge this. 🎉

Limit python setup.py test to our tests

---

httpbin/core.py
test_httpbin.py

In this commit:
- when we see a Transfer-Encoding: chunked request, and the server is gunicorn,
we set environ wsgi.input_terminated, which is required by Werkzeug in the
absence of Content-Lenght, or it will empty the data stream.
- for chunked requests to non-gunicorn, return 501 Not Implemented.
Looking for guidance on the best way to set-up an acceptance/system test for this, since it cannot be verified through unit tests using FlaskClient.

Added support for chunked encoded requests when running gunicorn. #340

---

httpbin/core.py
test_httpbin.py

This should resolve the issue in #415. We had a regression around when we send digest-auth challenges with #366 and later #392. This will now verify what kind of 'Authorization' header we received and send a challenge if the value isn't `digest xxxxxxxxxx`.

Send digest-auth challenge for wrong Authorization header

---

httpbin/templates/httpbin.1.html

I have come to find out that the /base64/:value endpoint isn't documented on the index.html page, I'm suggesting adding this into that page.

document decode_base64 endpoint /base64/:value on the index.html

---

httpbin/core.py
test_httpbin.py

RFC 7232, section 4.1 specifies that when returning a 304 status code the
ETag header must also be included if it would have been sent in a 200 (OK)
response.

Return ETag header with 304 response

---

httpbin/core.py
httpbin/templates/flasgger/index.html
httpbin/templates/footer.html

- Categorized endpoints (by tags)
- Adjusted missing  endpoints
- Added /legacy as a path to old style website
- Scheme will default to `window.location.protocol` so if user access in https it will work
- Customized the `flasgger/index.html` template (removed topbar)
- added footer for info
- added `fork me on github` badge
Pictures
> removed the green top header to be a minimalist and clean website

Adjusts in layout + categorized endpoints

---

httpbin/core.py

This fixes the SwaggerUI for `redirect-to` requests, but properly passing `url` and optionally `status_code` as query-strings.
What is not fixed here is ... currently all methods `GET` `POST` go through the same method - both `GET` and `POST` are fixed here, but really `POST` should use `formData` and a body to pass the parameters - it is fixed here but is using queryString same as `GET`.
Fixed #476.

Added url and status_code as query-string parameters for SwaggerUI

---

.dockerignore

Adds a `.dockerignore` file to instruct Docker to exclude `Dockerfile` from the build-context.  This has two effects:
1. Stops `Dockerfile` from being added to the image under `/httpbin`.  There's no point in it being there, and it might be confusing.
1. More importantly, it improves build caching.  In the current `Dockerfile` the statement `ADD . /httpbin` will add the `Dockerfile` along with everything else, and will cause a cache-miss for this line for edits of `Dockerfile`.  This could be annoying if editing lines after the `ADD` line, as it will cause unnecessary execution of `pip3` etc. for no reason.
This change doesn't do anything to effect normal Docker cache-invalidation when the `Dockerfile` is edited as-normal ... if just prevents changes in the text-file `Dockerfile`, …

Added a .dockerignore file to ignore Dockerfile

---

httpbin/core.py

We have code that only does POST requests so the method is fixed to be POST. Still, we'd like to test that code so we need `/delay` to work with POST as well.
Since I was already at it I've added other methods often used with other endpoints as well.
This fixes issues like #338.

Support more HTTP methods for /delay

---

httpbin/core.py

Previously httpbin used to return pretty-printed JSON, which was easy to read when viewing raw responses. But now the responses are minified.
httpbin uses Flask, and Flask 1.0 [changed the default](http://flask.pocoo.org/docs/1.0/changelog/#version-1-0) for [`JSONIFY_PRETTYPRINT_REGULAR`](http://flask.pocoo.org/docs/1.0/config/#JSONIFY_PRETTYPRINT_REGULAR) to `False`, which is what probably caused the change in httpbin's behavior.
This PR explicitly sets [`JSONIFY_PRETTYPRINT_REGULAR`](http://flask.pocoo.org/docs/1.0/config/#JSONIFY_PRETTYPRINT_REGULAR) to `True` to pretty-print JSON responses.

Pretty-print JSON responses

---

MANIFEST.in

Removed `requirements.txt` which was removed when the migration to `pipenv`/`Pipfile` occurred.
Fixed `README.md` mention - notably this file has toggled more than once between `README.rst` and `README.md` but I assume it is stable now.

Manifest fixes

---

httpbin/core.py
test_httpbin.py

There are currently two issues with `/bearer`:
1. It accepts any `Authorization` header, e.g.
```
Authorization: Basic ...
Authorization: 123abc
```
rather than just `Authorization: Bearer ...` as defined by [RFC 6750](https://tools.ietf.org/html/rfc6750#section-2.1).
2) If the bearer token starts with a combination of characters `aBer`, the returned `token` has these characters removed. This is caused by using [`lstrip`](https://docs.python.org/3/library/stdtypes.html#str.lstrip):
```
token = authorization.lstrip('Bearer ')
```
The issue happens because the argument of `lstrip` is not a prefix, but a set of characters to be removed.
This PR fixes both issues and adds the corresponding tests.

Fix incorrect /bearer behavior

---

httpbin/core.py
test_httpbin.py

If `show_env` is True, then return all the headers without stripping `ENV_HEADERS`. Also adds tests for `/headers` endpoint.
Signed-off-by: Sanket Saurav <sanketsaurav@gmail.com>

Fix #454: Support `show_env` param in `/headers`

---

README.md

hurl.it is not reachable as shown below. 
curl -v https://www.hurl.it
* Rebuilt URL to: https://www.hurl.it/
* Hostname was NOT found in DNS cache
*   Trying 184.95.38.200...
* connect to 184.95.38.200 port 443 failed: Connection refused
* Failed to connect to www.hurl.it port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.hurl.it port 443: Connection refused

Removed hurl.it which is not reachable from references

---

httpbin/core.py
test_httpbin.py

Reverts #457. Fixes #487.
The docstring typo fixes are retained, along with the additional tests,
modified to revert to the original `"headers": {` dict format.
The reverted change `get_dict('headers')` -> `get_headers()` was not required. The
query-string `?show_env=1` was already effective in allowing env headers to be
returned.
This partially reverts commit 31ffe79981a079d6605352d2d84de2f2d27ab6db.
That this change was not required (other than the tests, thanks) was hinted-at by @nateprewitt in the review for #457:
> I'm not sure if get_dict change is needed, although it probably won't hurt anything either. I'd definitely like to see the tests merged at the least though.
In fact the `show_env` pass-through option for filtered env headers has been there since that feature was added in …

Revert #457 "Support `show_env` param in `/headers`"

---

.dockerignore

Another small Docker build-cache fix.  Since we `ADD . /httpbin`, this is collecting the local `.git`.  Changes in the state of the local Git repo should not invalidate the Docker build cache.
To test, before/after:
`docker build ...`
then
`docker build ...` (cached)
then
`git commit --allow-empty -m "empty"`
then
`docker build ...`
Currently the last build will cause a cache-miss ... after this change it will not.

Changes in the local Git db should not invalidate Docker build cache

---

httpbin/templates/flasgger/index.html

Fixes:
GET http://httpbin.org/flasgger_static/%20lib/jquery.min.js 404 (NOT FOUND)

Removed (another) stray space from static path for jquery js

---

AUTHORS
app.json

The existing url redirects fine, but we may as well use the direct one.
Also appended to AUTHORS.

Corrected repository URL in app.json

---

Dockerfile

Been experimenting with `pipenv` for reproducible Docker image builds and came-up with this approach for _httpbin_.
It makes a couple of Docker cacheability improvements - mainly because `Pipfile` and `Pipfile.lock` are added on their own before deps are installed, so changes to the rest of the source-code won't cause a cache-miss and re-download of all the dependencies.
I'm curious as to whether this is an intended use of `pipenv` ... it seems to help solve the problems for installing as _Applications_ (versus _Libraries_) with pinned versions for dependencies for a specific build.
With reference to #493, with this change the built Docker image should contain `greenlet` version `0.14.3` (the locked version), and not the latest `0.14.4` which would be resolved by `setup.py`.
Fixed #493.

Dockerfile: Resolve deps using pipenv/Pipefile(.lock)
